country_subregion = {
'Abkhazia': 'Eastern Europe',
 'Afghanistan': 'Southern Asia',
 'Albania': 'Southern Europe',
 'Algeria': 'Northern Africa',
 'American Samoa': 'Polynesia',
 'Andorra': 'Southern Europe',
 'Angola': 'Sub-Saharan Africa',
 'Anguilla': 'Latin America and the Caribbean',
 'Antigua and Barbuda': 'Latin America and the Caribbean',
 'Argentina': 'Latin America and the Caribbean',
 'Armenia': 'Western Asia',
 'Aruba': 'Latin America and the Caribbean',
 'Australia': 'Australia and New Zealand',
 'Austria': 'Western Europe',
 'Azerbaijan': 'Western Asia',
 'Bahamas': 'Latin America and the Caribbean',
 'Bahrain': 'Western Asia',
 'Bangladesh': 'Southern Asia',
 'Barbados': 'Latin America and the Caribbean',
 'Belarus': 'Eastern Europe',
 'Belgium': 'Western Europe',
 'Belize': 'Latin America and the Caribbean',
 'Benin': 'Sub-Saharan Africa',
 'Bermuda': 'Northern America',
 'Bhutan': 'Southern Asia',
 'Bolivia': 'Latin America and the Caribbean',
 'Bosnia and Herzegovina': 'Southern Europe',
 'Botswana': 'Sub-Saharan Africa',
 'Brazil': 'Latin America and the Caribbean',
 'British Virgin Islands': 'Latin America and the Caribbean',
 'Brunei Darussalam': 'South-eastern Asia',
 'Bulgaria': 'Eastern Europe',
 'Burkina Faso': 'Sub-Saharan Africa',
 'Burundi': 'Sub-Saharan Africa',
 'Cabo Verde': 'Sub-Saharan Africa',
 'Cambodia': 'South-eastern Asia',
 'Cameroon': 'Sub-Saharan Africa',
 'Canada': 'Northern America',
 'Cayman Islands': 'Latin America and the Caribbean',
 'Central African Republic': 'Sub-Saharan Africa',
 'Chad': 'Sub-Saharan Africa',
 'Chile': 'Latin America and the Caribbean',
 'China': 'Eastern Asia',
 'Christmas Island': 'Australia and New Zealand',
 'Colombia': 'Latin America and the Caribbean',
 'Comoros': 'Sub-Saharan Africa',
 'Congo': 'Sub-Saharan Africa',
 'Cook Islands': 'Polynesia',
 'Costa Rica': 'Latin America and the Caribbean',
 "Cote d'Ivoire": 'Sub-Saharan Africa',
 'Croatia': 'Southern Europe',
 'Cuba': 'Latin America and the Caribbean',
 'Cyprus': 'Southern Europe',
 'Czechia': 'Eastern Europe',
 'Democratic Republic of the Congo': 'Sub-Saharan Africa',
 'Denmark': 'Northern Europe',
 'Djibouti': 'Sub-Saharan Africa',
 'Dominica': 'Latin America and the Caribbean',
 'Dominican Republic': 'Latin America and the Caribbean',
 'East Timor': 'South-eastern Asia',
 'Easter Island': 'Polynesia',
 'Ecuador': 'Latin America and the Caribbean',
 'Egypt': 'Northern Africa',
 'El Salvador': 'Latin America and the Caribbean',
 'Equatorial Guinea': 'Sub-Saharan Africa',
 'Eritrea': 'Sub-Saharan Africa',
 'Estonia': 'Northern Europe',
 'Eswatini': 'Sub-Saharan Africa',
 'Ethiopia': 'Sub-Saharan Africa',
 'Falkland Islands': 'Latin America and the Caribbean',
 'Faroe Islands': 'Northern Europe',
 'Fiji': 'Melanesia',
 'Finland': 'Northern Europe',
 'France': 'Western Europe',
 'French Guiana': 'Latin America and the Caribbean',
 'French Polynesia': 'Polynesia',
 'Gabon': 'Sub-Saharan Africa',
 'Gambia': 'Sub-Saharan Africa',
 'Georgia': 'Western Asia',
 'Germany': 'Western Europe',
 'Ghana': 'Sub-Saharan Africa',
 'Gibraltar': 'Southern Europe',
 'Greece': 'Southern Europe',
 'Greenland': 'Northern America',
 'Grenada': 'Latin America and the Caribbean',
 'Guadeloupe': 'Latin America and the Caribbean',
 'Guam': 'Micronesia',
 'Guatemala': 'Latin America and the Caribbean',
 'Guernsey': 'Northern Europe',
 'Guinea': 'Sub-Saharan Africa',
 'Guinea-Bissau': 'Sub-Saharan Africa',
 'Guyana': 'Latin America and the Caribbean',
 'Haiti': 'Latin America and the Caribbean',
 'Honduras': 'Latin America and the Caribbean',
 'Hong Kong': 'Eastern Asia',
 'Hungary': 'Eastern Europe',
 'Iceland': 'Northern Europe',
 'India': 'Southern Asia',
 'Indonesia': 'South-eastern Asia',
 'Iran': 'Southern Asia',
 'Iraq': 'Western Asia',
 'Ireland': 'Northern Europe',
 'Isle of Man': 'Northern Europe',
 'Israel': 'Western Asia',
 'Italy': 'Southern Europe',
 'Jamaica': 'Latin America and the Caribbean',
 'Japan': 'Eastern Asia',
 'Jersey': 'Northern Europe',
 'Jordan': 'Western Asia',
 'Kazakhstan': 'Central Asia',
 'Kenya': 'Sub-Saharan Africa',
 'Kiribati': 'Micronesia',
 'Kuwait': 'Western Asia',
 'Kyrgyzstan': 'Central Asia',
 'Laos': 'South-eastern Asia',
 'Latvia': 'Northern Europe',
 'Lebanon': 'Western Asia',
 'Lesotho': 'Sub-Saharan Africa',
 'Liberia': 'Sub-Saharan Africa',
 'Libya': 'Northern Africa',
 'Liechtenstein': 'Western Europe',
 'Lithuania': 'Northern Europe',
 'Luxembourg': 'Western Europe',
 'Macao': 'Eastern Asia',
 'Madagascar': 'Sub-Saharan Africa',
 'Malawi': 'Sub-Saharan Africa',
 'Malaysia': 'South-eastern Asia',
 'Maldives': 'Southern Asia',
 'Mali': 'Sub-Saharan Africa',
 'Malta': 'Southern Europe',
 'Marshall Islands': 'Micronesia',
 'Martinique': 'Latin America and the Caribbean',
 'Mauritania': 'Sub-Saharan Africa',
 'Mauritius': 'Sub-Saharan Africa',
 'Mayotte': 'Sub-Saharan Africa',
 'Mexico': 'Latin America and the Caribbean',
 'Micronesia': 'Micronesia',
 'Moldova': 'Eastern Europe',
 'Monaco': 'Western Europe',
 'Mongolia': 'Eastern Asia',
 'Montenegro': 'Southern Europe',
 'Montserrat': 'Latin America and the Caribbean',
 'Morocco': 'Northern Africa',
 'Mozambique': 'Sub-Saharan Africa',
 'Myanmar': 'South-eastern Asia',
 'Nagorno-Karabakh Republic': 'Eastern Europe',
 'Namibia': 'Sub-Saharan Africa',
 'Nauru': 'Micronesia',
 'Nepal': 'Southern Asia',
 'Netherlands': 'Western Europe',
 'New Caledonia': 'Melanesia',
 'New Zealand': 'Australia and New Zealand',
 'Nicaragua': 'Latin America and the Caribbean',
 'Niger': 'Sub-Saharan Africa',
 'Nigeria': 'Sub-Saharan Africa',
 'Niue': 'Polynesia',
 'Norfolk Island': 'Australia and New Zealand',
 'North Korea': 'Eastern Asia',
 'North Macedonia': 'Southern Europe',
 'Northern Cyprus': 'Eastern Europe',
 'Northern Mariana Islands': 'Micronesia',
 'Norway': 'Northern Europe',
 'Oman': 'Western Asia',
 'Pakistan': 'Southern Asia',
 'Palau': 'Micronesia',
 'Panama': 'Latin America and the Caribbean',
 'Papua New Guinea': 'Melanesia',
 'Paraguay': 'Latin America and the Caribbean',
 'Peru': 'Latin America and the Caribbean',
 'Philippines': 'South-eastern Asia',
 'Poland': 'Eastern Europe',
 'Portugal': 'Southern Europe',
 'Puerto Rico': 'Latin America and the Caribbean',
 'Qatar': 'Western Asia',
 'Reunion': 'Sub-Saharan Africa',
 'Romania': 'Eastern Europe',
 'Russian Federation': 'Eastern Europe',
 'Rwanda': 'Sub-Saharan Africa',
 'Saint Kitts and Nevis': 'Latin America and the Caribbean',
 'Saint Lucia': 'Latin America and the Caribbean',
 'Saint Martin': 'Latin America and the Caribbean',
 'Saint Pierre and Miquelon': 'Northern America',
 'Saint Vincent and the Grenadines': 'Latin America and the Caribbean',
 'Samoa': 'Polynesia',
 'San Marino': 'Southern Europe',
 'Sao Tome and Principe': 'Sub-Saharan Africa',
 'Saudi Arabia': 'Western Asia',
 'Senegal': 'Sub-Saharan Africa',
 'Serbia': 'Southern Europe',
 'Seychelles': 'Sub-Saharan Africa',
 'Sierra Leone': 'Sub-Saharan Africa',
 'Singapore': 'South-eastern Asia',
 'Sint Maarten': 'Latin America and the Caribbean',
 'Slovakia': 'Eastern Europe',
 'Slovenia': 'Southern Europe',
 'Solomon Islands': 'Melanesia',
 'Somalia': 'Sub-Saharan Africa',
 'South Africa': 'Sub-Saharan Africa',
 'South Georgia and the South Sandwich Islands': 'Latin America and the '
                                                 'Caribbean',
 'South Korea': 'Eastern Asia',
 'South Sudan': 'Sub-Saharan Africa',
 'Spain': 'Southern Europe',
 'Sri Lanka': 'Southern Asia',
 'Sudan': 'Northern Africa',
 'Suriname': 'Latin America and the Caribbean',
 'Sweden': 'Northern Europe',
 'Switzerland': 'Western Europe',
 'Syria': 'Western Asia',
 'Taiwan': 'Eastern Asia',
 'Tajikistan': 'Central Asia',
 'Tanzania': 'Sub-Saharan Africa',
 'Thailand': 'South-eastern Asia',
 'Togo': 'Sub-Saharan Africa',
 'Tokelau': 'Polynesia',
 'Tonga': 'Polynesia',
 'Transnistria': 'Eastern Europe',
 'Trinidad and Tobago': 'Latin America and the Caribbean',
 'Tristan da Cunha': 'Latin America and the Caribbean',
 'Tunisia': 'Northern Africa',
 'Turkey': 'Western Asia',
 'Turkmenistan': 'Central Asia',
 'Turks and Caicos Islands': 'Latin America and the Caribbean',
 'Tuvalu': 'Polynesia',
 'U.S. Virgin Islands ': 'Latin America and the Caribbean',
 'Uganda': 'Sub-Saharan Africa',
 'Ukraine': 'Eastern Europe',
 'United Arab Emirates': 'Western Asia',
 'United Kingdom': 'Northern Europe',
 'United Kingdom; England': 'Northern Europe',
 'United States of America': 'Northern America',
 'Uruguay': 'Latin America and the Caribbean',
 'Uzbekistan': 'Central Asia',
 'Vanuatu': 'Melanesia',
 'Venezuela': 'Latin America and the Caribbean',
 'Viet Nam': 'South-eastern Asia',
 'Wallis and Futuna': 'Polynesia',
 'Western Sahara': 'Northern Africa',
 'Yemen': 'Western Asia',
 'Zambia': 'Sub-Saharan Africa',
 'Zimbabwe': 'Sub-Saharan Africa'
}
