country_capital_subregion = [

('Abkhazia', 'Sukhumi', 'Western Asia'),
 ('Afghanistan', 'Kabul', 'Southern Asia'),
 ('Albania', 'Tirana', 'Southern Europe'),
 ('Algeria', 'Algiers', 'Northern Africa'),
 ('American Samoa', 'Pago Pago', 'Polynesia'),
 ('Andorra', 'Andorra la Vella', 'Southern Europe'),
 ('Angola', 'Luanda', 'Sub-Saharan Africa'),
 ('Anguilla', 'The Valley', 'Latin America and the Caribbean'),
 ('Antigua and Barbuda', "St. John's", 'Latin America and the Caribbean'),
 ('Argentina', 'Buenos Aires', 'Latin America and the Caribbean'),
 ('Armenia', 'Yerevan', 'Western Asia'),
 ('Aruba', 'Oranjestad', 'Latin America and the Caribbean'),
 ('Australia', 'Canberra', 'Australia and New Zealand'),
 ('Austria', 'Vienna', 'Western Europe'),
 ('Azerbaijan', 'Baku', 'Western Asia'),
 ('Bahamas', 'Nassau', 'Latin America and the Caribbean'),
 ('Bahrain', 'Manama', 'Western Asia'),
 ('Bangladesh', 'Dhaka', 'Southern Asia'),
 ('Barbados', 'Bridgetown', 'Latin America and the Caribbean'),
 ('Belarus', 'Minsk', 'Eastern Europe'),
 ('Belgium', 'Brussels', 'Western Europe'),
 ('Belize', 'Belmopan', 'Latin America and the Caribbean'),
 ('Benin', 'Porto-Novo', 'Sub-Saharan Africa'),
 ('Bermuda', 'Hamilton', 'Northern America'),
 ('Bhutan', 'Thimphu', 'Southern Asia'),
 ('Bolivia', 'Sucre', 'Latin America and the Caribbean'),
 ('Bolivia', 'La Paz', 'Latin America and the Caribbean'),
 ('Bosnia and Herzegovina', 'Sarajevo', 'Southern Europe'),
 ('Botswana', 'Gaborone', 'Sub-Saharan Africa'),
 ('Brazil', 'Brasilia', 'Latin America and the Caribbean'),
 ('British Virgin Islands', 'Road Town', 'Latin America and the Caribbean'),
 ('Brunei Darussalam', 'Bandar Seri Begawan', 'South-eastern Asia'),
 ('Bulgaria', 'Sofia', 'Eastern Europe'),
 ('Burkina Faso', 'Ouagadougou', 'Sub-Saharan Africa'),
 ('Burundi', 'Bujumbura', 'Sub-Saharan Africa'),
 ('Cabo Verde', 'Praia', 'Sub-Saharan Africa'),
 ('Cambodia', 'Phnom Penh', 'South-eastern Asia'),
 ('Cameroon', 'Yaounde', 'Sub-Saharan Africa'),
 ('Canada', 'Ottawa', 'Northern America'),
 ('Cayman Islands', 'George Town', 'Latin America and the Caribbean'),
 ('Central African Republic', 'Bangui', 'Sub-Saharan Africa'),
 ('Chad', "N'Djamena", 'Sub-Saharan Africa'),
 ('Chile', 'Santiago', 'Latin America and the Caribbean'),
 ('China', 'Beijing', 'Eastern Asia'),
 ('Christmas Island', 'Flying Fish Cove', 'Australia and New Zealand'),
 ('Colombia', 'Bogota', 'Latin America and the Caribbean'),
 ('Comoros', 'Moroni', 'Sub-Saharan Africa'),
 ('Congo', 'Brazzaville', 'Sub-Saharan Africa'),
 ('Cook Islands', 'Avarua', 'Polynesia'),
 ('Costa Rica', 'San Jose', 'Latin America and the Caribbean'),
 ("Cote d'Ivoire", 'Yamoussoukro', 'Sub-Saharan Africa'),
 ('Croatia', 'Zagreb', 'Southern Europe'),
 ('Cuba', 'Havana', 'Latin America and the Caribbean'),
 ('Cyprus', 'Nicosia', 'Southern Europe'),
 ('Czechia', 'Prague', 'Eastern Europe'),
 ('Democratic Republic of the Congo', 'Kinshasa', 'Sub-Saharan Africa'),
 ('Denmark', 'Copenhagen', 'Northern Europe'),
 ('Djibouti', 'Djibouti', 'Sub-Saharan Africa'),
 ('Dominica', 'Roseau', 'Latin America and the Caribbean'),
 ('Dominican Republic', 'Santo Domingo', 'Latin America and the Caribbean'),
 ('East Timor', 'Dili', 'South-eastern Asia'),
 ('Easter Island', 'Hanga Roa', 'Polynesia'),
 ('Ecuador', 'Quito', 'Latin America and the Caribbean'),
 ('Egypt', 'Cairo', 'Northern Africa'),
 ('El Salvador', 'San Salvador', 'Latin America and the Caribbean'),
 ('Equatorial Guinea', 'Malabo', 'Sub-Saharan Africa'),
 ('Eritrea', 'Asmara', 'Sub-Saharan Africa'),
 ('Estonia', 'Tallinn', 'Northern Europe'),
 ('Eswatini', 'Mbabane', 'Sub-Saharan Africa'),
 ('Ethiopia', 'Addis Ababa', 'Sub-Saharan Africa'),
 ('Falkland Islands', 'Stanley', 'Latin America and the Caribbean'),
 ('Faroe Islands', 'Torshavn', 'Northern Europe'),
 ('Fiji', 'Suva', 'Melanesia'),
 ('Finland', 'Helsinki', 'Northern Europe'),
 ('France', 'Paris', 'Western Europe'),
 ('French Guiana', 'Cayenne', 'Latin America and the Caribbean'),
 ('French Polynesia', 'Papeete', 'Polynesia'),
 ('Gabon', 'Libreville', 'Sub-Saharan Africa'),
 ('Gambia', 'Banjul', 'Sub-Saharan Africa'),
 ('Georgia', 'Tbilisi', 'Western Asia'),
 ('Germany', 'Berlin', 'Western Europe'),
 ('Ghana', 'Accra', 'Sub-Saharan Africa'),
 ('Gibraltar', 'Gibraltar', 'Southern Europe'),
 ('Greece', 'Athens', 'Southern Europe'),
 ('Greenland', 'Nuuk', 'Northern America'),
 ('Grenada', "St. George's", 'Latin America and the Caribbean'),
 ('Guadeloupe', 'Basse Terre', 'Latin America and the Caribbean'),
 ('Guam', 'Hagatna', 'Micronesia'),
 ('Guatemala', 'Guatemala City', 'Latin America and the Caribbean'),
 ('Guernsey', 'St. Peter Port', 'Northern Europe'),
 ('Guinea', 'Conakry', 'Sub-Saharan Africa'),
 ('Guinea-Bissau', 'Bissau', 'Sub-Saharan Africa'),
 ('Guyana', 'Georgetown', 'Latin America and the Caribbean'),
 ('Haiti', 'Port-au-Prince', 'Latin America and the Caribbean'),
 ('Honduras', 'Tegucigalpa', 'Latin America and the Caribbean'),
 ('Hong Kong', 'Hong Kong', 'Eastern Asia'),
 ('Hungary', 'Budapest', 'Eastern Europe'),
 ('Iceland', 'Reykjavik', 'Northern Europe'),
 ('India', 'New Delhi', 'Southern Asia'),
 ('Indonesia', 'Jakarta', 'South-eastern Asia'),
 ('Iran', 'Tehran', 'Southern Asia'),
 ('Iraq', 'Baghdad', 'Western Asia'),
 ('Ireland', 'Dublin', 'Northern Europe'),
 ('Isle of Man', 'Douglas', 'Northern Europe'),
 ('Israel', 'Jerusalem', 'Western Asia'),
 ('Italy', 'Rome', 'Southern Europe'),
 ('Jamaica', 'Kingston', 'Latin America and the Caribbean'),
 ('Japan', 'Tokyo', 'Eastern Asia'),
 ('Jersey', 'St. Helier', 'Northern Europe'),
 ('Jordan', 'Amman', 'Western Asia'),
 ('Kazakhstan', 'Astana', 'Central Asia'),
 ('Kenya', 'Nairobi', 'Sub-Saharan Africa'),
 ('Kiribati', 'Tarawa', 'Micronesia'),
 ('Kuwait', 'Kuwait City', 'Western Asia'),
 ('Kyrgyzstan', 'Bishkek', 'Central Asia'),
 ('Laos', 'Vientiane', 'South-eastern Asia'),
 ('Latvia', 'Riga', 'Northern Europe'),
 ('Lebanon', 'Beirut', 'Western Asia'),
 ('Lesotho', 'Maseru', 'Sub-Saharan Africa'),
 ('Liberia', 'Monrovia', 'Sub-Saharan Africa'),
 ('Libya', 'Tripoli', 'Northern Africa'),
 ('Liechtenstein', 'Vaduz', 'Western Europe'),
 ('Lithuania', 'Vilnius', 'Northern Europe'),
 ('Luxembourg', 'Luxembourg', 'Western Europe'),
 ('Macao', 'Macao', 'Eastern Asia'),
 ('Madagascar', 'Antananarivo', 'Sub-Saharan Africa'),
 ('Malawi', 'Lilongwe', 'Sub-Saharan Africa'),
 ('Malaysia', 'Kuala Lumpur', 'South-eastern Asia'),
 ('Maldives', 'Male', 'Southern Asia'),
 ('Mali', 'Bamako', 'Sub-Saharan Africa'),
 ('Malta', 'Valletta', 'Southern Europe'),
 ('Marshall Islands', 'Majuro', 'Micronesia'),
 ('Martinique', 'Fort-de-France-bay', 'Latin America and the Caribbean'),
 ('Mauritania', 'Nouakchott', 'Sub-Saharan Africa'),
 ('Mauritius', 'Port Louis', 'Sub-Saharan Africa'),
 ('Mayotte', 'Mamoudzou', 'Sub-Saharan Africa'),
 ('Mexico', 'Mexico City', 'Latin America and the Caribbean'),
 ('Micronesia', 'Palikir', 'Micronesia'),
 ('Moldova', 'Chisinau', 'Eastern Europe'),
 ('Monaco', 'Monaco', 'Western Europe'),
 ('Mongolia', 'Ulaanbaatar', 'Eastern Asia'),
 ('Montenegro', 'Podgorica', 'Southern Europe'),
 ('Montserrat', 'Plymouth', 'Latin America and the Caribbean'),
 ('Morocco', 'Rabat', 'Northern Africa'),
 ('Mozambique', 'Maputo', 'Sub-Saharan Africa'),
 ('Myanmar', 'Naypyidaw', 'South-eastern Asia'),
 ('Nagorno-Karabakh Republic', 'Stepanakert', 'Western Asia'),
 ('Namibia', 'Windhoek', 'Sub-Saharan Africa'),
 ('Nauru', 'Yaren', 'Micronesia'),
 ('Nepal', 'Kathmandu', 'Southern Asia'),
 ('Netherlands', 'Amsterdam', 'Western Europe'),
 ('New Caledonia', 'Noumea', 'Melanesia'),
 ('New Zealand', 'Wellington', 'Australia and New Zealand'),
 ('Nicaragua', 'Managua', 'Latin America and the Caribbean'),
 ('Niger', 'Niamey', 'Sub-Saharan Africa'),
 ('Nigeria', 'Abuja', 'Sub-Saharan Africa'),
 ('Niue', 'Alofi', 'Polynesia'),
 ('Norfolk Island', 'Kingston', 'Australia and New Zealand'),
 ('North Korea', 'Pyongyang', 'Eastern Asia'),
 ('North Macedonia', 'Skopje', 'Southern Europe'),
 ('Northern Mariana Islands', 'Saipan', 'Micronesia'),
 ('Norway', 'Oslo', 'Northern Europe'),
 ('Oman', 'Muscat', 'Western Asia'),
 ('Pakistan', 'Islamabad', 'Southern Asia'),
 ('Palau', 'Ngerulmud', 'Micronesia'),
 ('Panama', 'Panama City', 'Latin America and the Caribbean'),
 ('Papua New Guinea', 'Port Moresby', 'Melanesia'),
 ('Paraguay', 'Asuncion', 'Latin America and the Caribbean'),
 ('Peru', 'Lima', 'Latin America and the Caribbean'),
 ('Philippines', 'Manila', 'South-eastern Asia'),
 ('Poland', 'Warsaw', 'Eastern Europe'),
 ('Portugal', 'Lisbon', 'Southern Europe'),
 ('Puerto Rico', 'San Juan', 'Latin America and the Caribbean'),
 ('Qatar', 'Doha', 'Western Asia'),
 ('Reunion', 'Saint-Denis', 'Sub-Saharan Africa'),
 ('Romania', 'Bucharest', 'Eastern Europe'),
 ('Russian Federation', 'Moscow', 'Eastern Europe'),
 ('Rwanda', 'Kigali', 'Sub-Saharan Africa'),
 ('Saint Kitts and Nevis', 'Basseterre', 'Latin America and the Caribbean'),
 ('Saint Lucia', 'Castries', 'Latin America and the Caribbean'),
 ('Saint Martin', 'Marigot', 'Latin America and the Caribbean'),
 ('Saint Pierre and Miquelon', 'St. Pierre', 'Northern America'),
 ('Saint Vincent and the Grenadines',
  'Kingstown',
  'Latin America and the Caribbean'),
 ('Samoa', 'Apia', 'Polynesia'),
 ('San Marino', 'San Marino', 'Southern Europe'),
 ('Sao Tome and Principe', 'Sao Tome', 'Sub-Saharan Africa'),
 ('Saudi Arabia', 'Riyadh', 'Western Asia'),
 ('Senegal', 'Dakar', 'Sub-Saharan Africa'),
 ('Serbia', 'Belgrade', 'Southern Europe'),
 ('Seychelles', 'Victoria', 'Sub-Saharan Africa'),
 ('Sierra Leone', 'Freetown', 'Sub-Saharan Africa'),
 ('Singapore', 'Singapore', 'South-eastern Asia'),
 ('Sint Maarten', 'Philipsburg', 'Latin America and the Caribbean'),
 ('Slovakia', 'Bratislava', 'Eastern Europe'),
 ('Slovenia', 'Ljubljana', 'Southern Europe'),
 ('Solomon Islands', 'Honiara', 'Melanesia'),
 ('Somalia', 'Mogadishu', 'Sub-Saharan Africa'),
 ('South Africa', 'Pretoria', 'Sub-Saharan Africa'),
 ('South Georgia and the South Sandwich Islands',
  'Grytviken',
  'Latin America and the Caribbean'),
 ('South Korea', 'Seoul', 'Eastern Asia'),
 ('South Sudan', 'Juba', 'Sub-Saharan Africa'),
 ('Spain', 'Madrid', 'Southern Europe'),
 ('Sri Lanka', 'Colombo', 'Southern Asia'),
 ('Sudan', 'Khartoum', 'Northern Africa'),
 ('Suriname', 'Paramaribo', 'Latin America and the Caribbean'),
 ('Sweden', 'Stockholm', 'Northern Europe'),
 ('Switzerland', 'Bern', 'Western Europe'),
 ('Syria', 'Damascus', 'Western Asia'),
 ('Taiwan', 'Taipei', 'Eastern Asia'),
 ('Tajikistan', 'Dushanbe', 'Central Asia'),
 ('Tanzania', 'Dodoma', 'Sub-Saharan Africa'),
 ('Thailand', 'Bangkok', 'South-eastern Asia'),
 ('Togo', 'Lome', 'Sub-Saharan Africa'),
 ('Tokelau', 'Nukunonu', 'Polynesia'),
 ('Tonga', "Nuku'alofa", 'Polynesia'),
 ('Transnistria', 'Tiraspol', 'Eastern Europe'),
 ('Trinidad and Tobago', 'Port of Spain', 'Latin America and the Caribbean'),
 ('Tristan da Cunha',
  'Edinburgh of the Seven Seas',
  'Latin America and the Caribbean'),
 ('Tunisia', 'Tunis', 'Northern Africa'),
 ('Turkey', 'Ankara', 'Western Asia'),
 ('Turkmenistan', 'Ashgabat', 'Central Asia'),
 ('Turks and Caicos Islands',
  'Cockburn Town',
  'Latin America and the Caribbean'),
 ('Tuvalu', 'Funafuti', 'Polynesia'),
 ('U.S. Virgin Islands ',
  'Charlotte Amalie',
  'Latin America and the Caribbean'),
 ('Uganda', 'Kampala', 'Sub-Saharan Africa'),
 ('Ukraine', 'Kiev', 'Eastern Europe'),
 ('United Arab Emirates', 'Abu Dhabi', 'Western Asia'),
 ('United Kingdom', 'London', 'Northern Europe'),
 ('United States of America', 'Washington, D.C.', 'Northern America'),
 ('Uruguay', 'Montevideo', 'Latin America and the Caribbean'),
 ('Uzbekistan', 'Tashkent', 'Central Asia'),
 ('Vanuatu', 'Port Vila', 'Melanesia'),
 ('Venezuela', 'Caracas', 'Latin America and the Caribbean'),
 ('Viet Nam', 'Saigon', 'South-eastern Asia'),
 ('Wallis and Futuna', 'Mata-Utu', 'Polynesia'),
 ('Western Sahara', 'Laayoune', 'Northern Africa'),
 ('Yemen', "Sana'a", 'Western Asia'),
 ('Zambia', 'Lusaka', 'Sub-Saharan Africa'),
 ('Zimbabwe', 'Harare', 'Sub-Saharan Africa')]
